"""create dictionary tables

Revision ID: 69d2118e1afc
Revises: 7c19bf2b8901
Create Date: 2026-04-12 08:08:45.237388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69d2118e1afc'
down_revision: Union[str, None] = '7c19bf2b8901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dict_cigarette',
    sa.Column('product_code', sa.String(length=30), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('brand_owner', sa.String(length=100), nullable=True),
    sa.Column('price_category', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('dict_person',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id_card', sa.String(length=18), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('employment_type', sa.String(length=30), nullable=True),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.Column('degree', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_card')
    )
    op.create_table('dict_route',
    sa.Column('route_code', sa.String(length=30), nullable=False),
    sa.Column('route_name', sa.String(length=100), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('deliverer_id', sa.Integer(), nullable=True),
    sa.Column('customer_count', sa.Integer(), nullable=True),
    sa.Column('delivery_count', sa.Integer(), nullable=True),
    sa.Column('delivery_time', sa.String(length=50), nullable=True),
    sa.Column('settlement_time', sa.String(length=50), nullable=True),
    sa.Column('response_time_calc', sa.String(length=100), nullable=True),
    sa.Column('toll_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_cycle', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deliverer_id'], ['dict_person.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['dict_person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_code')
    )
    op.create_table('dict_vehicle',
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('cargo_size', sa.String(length=30), nullable=True),
    sa.Column('vehicle_type', sa.String(length=20), nullable=True),
    sa.Column('tank_or_battery_size', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mileage', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['dict_person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('dict_customer',
    sa.Column('customer_code', sa.String(length=30), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('settlement_method', sa.String(length=30), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('delivery_zone', sa.String(length=50), nullable=True),
    sa.Column('delivery_order', sa.Integer(), nullable=True),
    sa.Column('market_type', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['dict_route.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dict_customer')
    op.drop_table('dict_vehicle')
    op.drop_table('dict_route')
    op.drop_table('dict_person')
    op.drop_table('dict_cigarette')
    # ### end Alembic commands ###
